mongoimport --db community-planner --collection baseiconstyles --file ./baseiconstyles.json
mongoimport --db community-planner --collection circlemarkerstyles --file ./circlemarkerstyles.json
mongoimport --db community-planner --collection comments --file ./comments.json
mongoimport --db community-planner --collection diviconstyles --file ./diviconstyles.json
mongoimport --db community-planner --collection files --file ./files.json
mongoimport --db community-planner --collection fillstyles --file ./fillstyles.json
mongoimport --db community-planner --collection galleries --file ./galleries.json
mongoimport --db community-planner --collection geolayerdefinitions --file ./geolayerdefinitions.json
mongoimport --db community-planner --collection geolayers --file ./geolayers.json
mongoimport --db community-planner --collection iconstyles --file ./iconstyles.json
mongoimport --db community-planner --collection keyvaluepairs --file ./keyvaluepairs.json
mongoimport --db community-planner --collection linestyles --file ./linestyles.json
mongoimport --db community-planner --collection plans --file ./plans.json
mongoimport --db community-planner --collection plantexts --file ./plantexts.json
mongoimport --db community-planner --collection popupfunctions --file ./popupfunctions.json
mongoimport --db community-planner --collection posts --file ./posts.json
mongoimport --db community-planner --collection postcategories --file ./postcategories.json
mongoimport --db community-planner --collection simplefillstyles --file ./simplefillstyles.json
mongoimport --db community-planner --collection symbologyfunctions --file ./symbologyfunctions.json
mongoimport --db community-planner --collection tuples --file ./tuples.json
mongoimport --db community-planner --collection users --file ./users.json
