mongoexport --db community-planner --collection baseiconstyles --out baseiconstyles.json
mongoexport --db community-planner --collection circlemarkerstyles --out circlemarkerstyles.json
mongoexport --db community-planner --collection comments --out comments.json
mongoexport --db community-planner --collection diviconstyles --out diviconstyles.json
mongoexport --db community-planner --collection files --out files.json
mongoexport --db community-planner --collection fillstyles --out fillstyles.json
mongoexport --db community-planner --collection galleries --out galleries.json
mongoexport --db community-planner --collection geolayerdefinitions --out geolayerdefinitions.json
mongoexport --db community-planner --collection geolayers --out geolayers.json
mongoexport --db community-planner --collection iconstyles --out iconstyles.json
mongoexport --db community-planner --collection keyvaluepairs --out keyvaluepairs.json
mongoexport --db community-planner --collection linestyles --out linestyles.json
mongoexport --db community-planner --collection plans --out plans.json
mongoexport --db community-planner --collection plantexts --out plantexts.json
mongoexport --db community-planner --collection popupfunctions --out popupfunctions.json
mongoexport --db community-planner --collection posts --out posts.json
mongoexport --db community-planner --collection postcategories --out postcategories.json
mongoexport --db community-planner --collection simplefillstyles --out simplefillstyles.json
mongoexport --db community-planner --collection symbologyfunctions --out symbologyfunctions.json
mongoexport --db community-planner --collection tuples --out tuples.json
mongoexport --db community-planner --collection users --out users.json
